apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookdir-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookdir-app
  template:
    metadata:
      labels:
        app: bookdir-app
    spec:
      containers:
        - name: bookdir-app
          image: karthikeyan1512/mydocker_042:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bookdir-app-service
spec:
  selector:
    app: bookdir-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30009
  type: NodePort
